[package]
name = "ron-config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "0.7.0"
serde = "1.0.136"
derive_more = "0.99.17"